### ISSUE TITLE
Option to have "center" attribute 

### ISSUE THREAD

**Issue by IvanVelickovski** [avivharuzi/ngx-glide#13]
I was playing around with this wrapper in the last couple of days and I find it really cool and promising. 
I'm thinking of actually using it for my next Angular project.

However, I feel that it would be even better with additional "center" attribute as it's shown in the demo [here](https://avivharuzi.github.io/ngx-glide/).

If you set the "center" attribute to true in the demo you can have an output like this one: 

<img width="1429" alt="Screen Shot 2020-09-29 at 12 43 13 AM" src="https://user-images.githubusercontent.com/7550639/94493493-12401a80-01ed-11eb-80a1-748164ec883a.png">

**Comment by avivharuzi** [comment]
Yea I know it may be confusing because of the demo I choose the word center...
But it uses the **focusAt** input which can be number or string which is **"center"**
to add more input is useless...
Hope it helps you.

**Comment by IvanVelickovski** [comment]
I tried that but it doesn't seem to work. 
Even if you try it in your demo [here](https://stackblitz.com/edit/ngx-glide-demo-zokmmx?embed=1) it will show you an error `Property 'center' does not exist on type 'AppComponent'.`

<img width="1384" alt="Screen Shot 2020-09-29 at 10 10 10 AM" src="https://user-images.githubusercontent.com/7550639/94530851-fd3ea800-023b-11eb-8007-768660c2c147.png">

**Comment by IvanVelickovski** [comment]
Ah, nevermind, I should've used `focusAt` **without the brackets**. 
Thank you for your time.

I'm closing this one. :)
