### ISSUE TITLE
glide.esm.js:3243 Unable to preventDefault inside passive event listener invocation.

### ISSUE THREAD

**Issue by mattconvergent** [avivharuzi/ngx-glide#14]
**Describe the bug**
on any of the passive events IE: (move)="onMoved($event) throws the following error. not sure if theres a

**To Reproduce**
followed installation steps, add (move) action onto <ngx-slide> and error pops up when clicking arrows or sliding event

**Expected behavior**
behavior is working as expected, just throws the error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 
 - Browser: Chrome
 - Version: 87.0.4280.88 (Official Build) (x86_64)

**Comment by burnaDLX** [comment]
It looks like the problem is coming from the underlying library. You can find more info about this [here](https://github.com/glidejs/glide/issues/334).
