### ISSUE TITLE
Add a slide dynamically

### ISSUE THREAD

**Issue by The-Neo-Noir** [avivharuzi/ngx-glide#17]
Hi , 
From the Readme,  it seems that adding a new element is not supported. Is it still valid ?
Seems like glidejs do have a function called reinit which can do it.

**Comment by avivharuzi** [comment]
I did not see something like that in their documentation.
If you can put some URL reference to it...
I added in the last release a new function to update the carousel **recreate** via the component reference I need to add this to the README file.

**Comment by avivharuzi** [comment]
I updated the README
