### ISSUE TITLE
Remove private type on attribut in version 11.0.0

### ISSUE THREAD

**Issue by afreuDev** [avivharuzi/ngx-glide#18]
Hello, I'm a beginner in angular, and my app actually uses angular 11.
Following your instruction I pull the 11.0.1 version. But I can't personalize any options like "gap", "autoplay" cause they are private! Looks like you remove the "private" type on "Update angular to v12" commit, but that's use angular 12 and doesn't work anymore with my angular 11 apps.
Thx in advance for reading me!

**Comment by avivharuzi** [comment]
Yes, you're right it was private.
But why not pass the value in the template:
```html
<ngx-glide [gap]="10">
  ...
</ngx-glide>
```
This is the same result
