### ISSUE TITLE
Anchor element with [routerLink] disappears when dragging event ends

### ISSUE THREAD

**Issue by VRa3** [avivharuzi/ngx-glide#19]
Hello!

I noticed weird behaviour after I added anchor tag with [routerLink] attribute. It seems that whenever I end dragging the slide, anchor disappears for a moment and shows up again (see video). It doesn't seem like the element is destroyed in the dev tools, but I have no idea on that. If I change anchor element to span the problem is gone, so this is related only to **anchor with [routerLink]**

https://streamable.com/d0xhbz

Cheers!

**Comment by avivharuzi** [comment]
Hi, why would you change the route by navigating in the slides?
I don't know the code by I guess because you change the route the slides are initialized again.
This is not meant for routing.

**Comment by VRa3** [comment]
Hi @avivharuzi,

I think You misunderstood me. I don't change the route by navigating between the slides, I just have an anchor tag with [routerLink] which navigates after the click. When I change the slides I don't navigate ;) The problem is that, anchor tag disappears for a moment when drag event has been made

This is my markup, nothing else:

```
<ngx-glide class="fullscreen-slider" [type]="'slider'" [gap]="0" [showArrows]="false" [showBullets]="false">
  <div class="fullscreen-slider__slide">
      <div class="fullscreen-slider__text-wrapper">
          <div class="container">
              <h2 class="fullscreen-slider__heading">{{'WELCOME_TEXT.H1' | translate}}</h2>
              <p class="fullscreen-slider__paragraph">{{'WELCOME_TEXT.P1' | translate}}</p>
              <a [routerLink]="'/my-offer-view'" class="primary-outline-button">Button text</a>
          </div>
      </div>
  </div>
  
  + 1 more slide here
</ngx-slide>
```

**Comment by avivharuzi** [comment]
Sorry I didn't succeed to find the problem.
I'm closing the issue.
