### ISSUE TITLE
[type]="carousel" not working

### ISSUE THREAD

**Issue by maximilien0405** [avivharuzi/ngx-glide#22]
I'm trying to make the slider infinite with the type carousel attribute, but i have this error : 

`<ngx-glide #ngxGlide [type]="carousel" [peek]="{ before: 0, after: 100 }" [showArrows]="true" [gap]="20" [perView]="5" [showBullets]="false" [breakpoints]="this.breakpoints">
  ......
</ngx-glide>`

`Property 'carousel' does not exist on type 'HomeComponent'.`

How can i fix this ?

**Comment by avivharuzi** [comment]
It seems like you pass it wrong.
Try to type as string.
```html
<ngx-glide type="carousel">...</ngx-glide>
```

**Comment by maximilien0405** [comment]
It works ! Thanks :)
Probably should write that in the docs btw
