### ISSUE TITLE
how do i put two ngx components into one component?

### ISSUE THREAD

**Issue by juanicastellan0** [avivharuzi/ngx-glide#6]
I have two ngx glide on a landing page but I am having problems instantiating the second glide since it looks for it by the name of the glideel variable

I wish I could change the name of the variable that declares the main component to be able to instantiate two glides in one place

**Comment by avivharuzi** [comment]
Could you give some code example which can I look for the problem...

**Comment by juanicastellan0** [comment]
landing page:
![image](https://user-images.githubusercontent.com/37382853/84314568-ac952900-ab3e-11ea-995b-541a53ff8e51.png)
user-cards-carousel:
![image](https://user-images.githubusercontent.com/37382853/84314901-3b09aa80-ab3f-11ea-900f-7c153a52a862.png)
![image](https://user-images.githubusercontent.com/37382853/84314957-55dc1f00-ab3f-11ea-92c4-60b6ba2d956c.png)
accepted-payment-methods:
![image](https://user-images.githubusercontent.com/37382853/84314931-46f56c80-ab3f-11ea-829a-4b5fa9a7bd5c.png)
![image](https://user-images.githubusercontent.com/37382853/84315033-6db3a300-ab3f-11ea-9812-e91e318aa516.png)
glide-service:
![image](https://user-images.githubusercontent.com/37382853/84317464-2e875100-ab43-11ea-999a-7dbeb7edd65c.png)
console:
![image](https://user-images.githubusercontent.com/37382853/84315180-abb0c700-ab3f-11ea-8958-f8734fa8f509.png)

**Comment by avivharuzi** [comment]
Few things you can try:

1. Change ViewChild to specific element for example:

user-cards-carousel:

```html
<ngx-glide #userCardsCarouselGlide>...</ngx-glide>
```

```ts
@ViewChild('userCardsCarouselGlide', { static: false }) glide: NgxGlideComponent;
```

accepted-payment-methods:

```html
<ngx-glide #acceptedPaymentMethodsGlide>...</ngx-glide>
```

```ts
@ViewChild('acceptedPaymentMethodsGlide', { static: false }) glide: NgxGlideComponent;
```
2. Check your data is ready when declaring ngx-glide in HTML of what I see its looking OK but you can also make some extra code and add *ngIf for example:

```html
<ng-container *ngIf="user_comments && user_comments.length > 0">
  <ngx-glide #userCardsCarouselGlide>...</ngx-glide>
</ng-container>
```

3. Try to replace **(buildedBefore)="play()"** to **(mountedAfter)="play()"**

**Comment by ErrTem** [comment]
> Few things you can try:
> 
> 1. Change ViewChild to specific element for example:
> 
> user-cards-carousel:
> 
> ```
> <ngx-glide #userCardsCarouselGlide>...</ngx-glide>
> ```
> 
> ```ts
> @ViewChild('userCardsCarouselGlide', { static: false }) glide: NgxGlideComponent;
> ```
> 
> accepted-payment-methods:
> 
> ```
> <ngx-glide #acceptedPaymentMethodsGlide>...</ngx-glide>
> ```
> 
> ```ts
> @ViewChild('acceptedPaymentMethodsGlide', { static: false }) glide: NgxGlideComponent;
> ```
> 
> 2. Check your data is ready when declaring ngx-glide in HTML of what I see its looking OK but you can also make some extra code and add *ngIf for example:
> 
> ```
> <ng-container *ngIf="user_comments && user_comments.length > 0">
>   <ngx-glide #userCardsCarouselGlide>...</ngx-glide>
> </ng-container>
> ```
> 
> 3. Try to replace **(buildedBefore)="play()"** to **(mountedAfter)="play()"**

❤️ thanks a lot
