### ISSUE TITLE
Slider images are not responsive design

### ISSUE THREAD

**Issue by subrat7** [avivharuzi/ngx-glide#9]
[**Describe](url
![responsive](https://user-images.githubusercontent.com/12031027/89290722-e8e49180-d676-11ea-88aa-d50f1dafb62f.JPG)
) the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by avivharuzi** [comment]
It's can be done easily with breakpoints input to control the amount of views per breakpoint.

Example:

`
<ngx-glide ... [breakpoints]="{ '768': { perView: 1 }, '1200': { perView: 2 } }">...</ngx-glide>
`

You can check the demo again I updated it to be responsive: https://avivharuzi.github.io/ngx-glide/

**Comment by subrat7** [comment]
can you please deploy the demo code in stackblitz, so that I can plug and play the features
https://avivharuzi.github.io/ngx-glide/

Thanks for reply

**Comment by avivharuzi** [comment]
Enjoy: https://stackblitz.com/edit/ngx-glide-demo?embed=1
